### ISSUE TITLE
Doesn't work with objects

### ISSUE THREAD

**Issue by papa-smurf** [laracasts/PHP-Vars-To-Js-Transformer#34]
`$browserData = new stdClass;
JavaScript::put(['browserData' => $browserData]);`

Gives the following error: "The provided object needs a __toString() method". Converting the object to an array fixes this problem

**Comment by GrahamCampbell** [comment]
Just do this, surely?

```php
$browserData = new stdClass;
JavaScript::put(['browserData' => (array) $browserData]);
```

**Comment by GrahamCampbell** [comment]
Otherwise, you can see that we're trying to represent the object as a string rather than as it's properties which is what I assume you're trying to do.

**Comment by papa-smurf** [comment]
What I'm trying to understand is why an object requires a __toString method, why not simply handle them the same way you do (associative) arrays when it's missing? Of course I can cast it to an array but that doesn't add anything in terms of readability.

**Comment by ejaxon** [comment]
More to the point, it seems like there is an inconsistency in the way it treats stdClass objects. I am passing in two values: a stdClass object and an array of stdClass objects. It fails on the first. But if I remove that, it happily processes the second since it bypasses the test. The library just calls json_encode on the value, which encodes an array of stdClass objects. However, if that's correct behavior (and I believe it should be considered so), then refusing to translate a single object makes no sense.
